language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests. Yes there will be tests"

script:
  # Build Docker images
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tag the images
  - docker tag udagram-frontend dungnguyn713/udagram-frontend:v1
  - docker tag udagram-api-feed dungnguyn713/udagram-api-feed:v1
  - docker tag udagram-api-user dungnguyn713/udagram-api-user:v1
  - docker tag udagram-reverseproxy dungnguyn713/reverseproxy:v1

after_success:
  # Push the images to DockerHub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dungnguyn713/udagram-frontend:v1
  - docker push dungnguyn713/udagram-api-feed:v1
  - docker push dungnguyn713/udagram-api-user:v1
  - docker push dungnguyn713/reverseproxy:v1

# Optional: Specify branches to build
branches:
  only:
    - main
